# Dependencies
markdown:         	 kramdown
highlighter:      	 rouge

# Permalinks
permalink:           pretty

# Setup
title:            	'ESP8266 BR'
tagline:          	'Arduino para iniciantes'
description:      	'Tutoriais e dicas de desenvolvimento para ESP8266, Arduino, seus respectivos módulos e sensores.'
url:                 https://esp8266br.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Fabio Andrei Lorentz'
  url:               https://br.linkedin.com/in/fabiolorentz

# Custom vars
version:             1.0.0
